// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2lNQWpvz3ydZGZ3QVXRnTAL1I1agZ4Jo',
    appId: '1:223371884258:web:f11433db7487137f7550bb',
    messagingSenderId: '223371884258',
    projectId: 'keeps-ae624',
    authDomain: 'keeps-ae624.firebaseapp.com',
    storageBucket: 'keeps-ae624.appspot.com',
    measurementId: 'G-218J5HM9Y7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrWHcbRNj4-dWe-vZhnaSrbwHp9pea6sA',
    appId: '1:223371884258:android:5ad38044407f121e7550bb',
    messagingSenderId: '223371884258',
    projectId: 'keeps-ae624',
    storageBucket: 'keeps-ae624.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN_94kCcLSZRCoeKgSqO9zNUJ7RaeLifk',
    appId: '1:223371884258:ios:8706d516da1779f17550bb',
    messagingSenderId: '223371884258',
    projectId: 'keeps-ae624',
    storageBucket: 'keeps-ae624.appspot.com',
    iosBundleId: 'com.example.keeps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN_94kCcLSZRCoeKgSqO9zNUJ7RaeLifk',
    appId: '1:223371884258:ios:1a579eeae837a4ba7550bb',
    messagingSenderId: '223371884258',
    projectId: 'keeps-ae624',
    storageBucket: 'keeps-ae624.appspot.com',
    iosBundleId: 'com.example.keeps.RunnerTests',
  );
}
